In [1]:
import numpy as np

# Sigmoid function and its derivative
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

# Input dataset
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])
# Output dataset
y = np.array([[0], [0], [1], [1]])

# Seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

# Initiate weights randomly with mean 0
syn0 = 2 * np.random.random((3, 1)) - 1

for iter in range(10000):
    # Forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # How much did we miss?
    l1_error = y - l1

    # Multiply how much we missed by the slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, deriv=True)

    # Update weights
    syn0 += np.dot(l0.T, l1_delta)

print("Output After Training:")
print(l1)

Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


In [1]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))
x = np.array ([[0, 0, 1],
            [0, 1, 1],
            [1, 0, 1],
            [1, 1, 1]])

y=np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random ((3,1)) - 1

for iter in range (10000):

    l0 = x
    l1 = nonlin(np.dot(l0,syn0))

    l1_error = y - l1

    l1_delta = l1_error * nonlin(l1,True)

    syn0 += np.dot (l0.T,l1_delta)

print ("output after training:")
print (l1)


    

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np

def nonlin (x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x= np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y=np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))

    l1_error = y - l1

    l1_delta = l1_error*nonlin(l1,True)

    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")

print (l1)

    

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [2]:
import numpy as np
def nonlin(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1], 
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y=np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0=x
    l1=nonlin(np.dot(l0,syn0))

    l1_error = y - l1

    l1_delta = l1_error*nonlin(l1,True)

    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [4]:
import numpy as np
def nonlin(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot (l0.T,l1_delta)

print ("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [6]:
import numpy as np
def nonline (x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print ("output after trainig")

print(l1)

output after trainig
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [7]:
import numpy as np
def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")

print(l1)


output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [8]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [10]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [19]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,5],
               [0,5,5],
               [5,0,5],
               [5,5,5]])

y = np.array([[0,0,5,5]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")

print (l1)



output after training
[[0.99999997]
 [1.        ]
 [1.        ]
 [1.        ]]


In [16]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [22]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")

print(l1)


output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [25]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range(1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")

print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [29]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y=np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0= 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")
print (l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [30]:
import numpy as np

def nonlin(x, deriv = False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y -l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot (l0.T,l1_delta)

print("output after training")
print(l1)


output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [35]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv== True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x=np.array ([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0 += np.dot(l0.T,l1_delta)

print("output after training")
print(l1)

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [3]:
import numpy as np

def nonlin(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0=2*np.random.random((3,1))-1

for iter in range (1000):
    l0=x
    l1=nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0+=np.dot(l0.T,l1_delta)

print("output after training")
print(l1)



output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [5]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,0,1,1,]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1))-1

for itern in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*(nonlin(l1,True))
    syn0 += np.dot(l0.T,l1_delta)

print ("output after training")
print(l1)
    

output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [10]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4))-1
syn1 = 2*np.random.random((4,1))-1

for j in range(60000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin (np.dot(l1,syn1))
    l2_error = y - l2

    if (j% 10000) == 0:
        print ("Error:",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)

    l1_error = l2_delta.dot(syn1.T)

    ## uses the "confidence weighted error" from l2 to establish an error for l1. 
    # To do this, it simply sends the error across the weights from l2 to l1. 
    # This gives what you could call a "contribution weighted error" because we learn how much 
    # each node value in l1 "contributed" to the error in l2. This step is called "backpropagating" 
    # and is the namesake of the algorithm. We then update syn0 using the same steps we did in the 2 layer implementation.

    l1_delta = l1_error*nonlin(l1,True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error: 0.49641003190272537
Error: 0.008584525653247153
Error: 0.005789459862507809
Error: 0.004629176776769983
Error: 0.0039587652802736475
Error: 0.0035101225678616744


In [21]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4))-1
syn1 = 2*np.random.random ((4,1))-1

for j in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    
    l1_error = np.dot(l2_delta,syn1.T)

    l1_delta = l1_error*nonlin(l1,True)

    syn1+= l1.T.dot(l2_delta)
    syn0 += np.dot(l0.T,l1_delta)
    
    

Error 0.49641003190272537
Error 0.008584525653247153
Error 0.005789459862507809
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.0035101225678616744


In [23]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,0,1,1]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,1)) - 1

for iter in range (1000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l1_error = y - l1
    l1_delta = l1_error*nonlin(l1,True)
    syn0+=np.dot(l0.T,l1_delta)

print("output after training")
print(l1)








output after training
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]


In [25]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin (np.dot(l1,syn1))
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)

    l1_error = np.dot(l2_delta,syn1.T)

    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot (l1.T,l2_delta)
    syn0 += np.dot (l0.T,l1_delta)

Error 0.49641003190272537
Error 0.008584525653247153
Error 0.005789459862507809
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.0035101225678616744


In [38]:
import numpy as np

def nonlin (x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random ((4,1)) - 1

for j in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y -l2

    if (j% 10000) == 0:
        print("Error",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    
    l1_error = np.dot(l2_delta,syn1.T)
    
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot (l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)



Error 0.49641003190272537
Error 0.008584525653247153
Error 0.005789459862507809
Error 0.004629176776769983
Error 0.005789459862507809
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.0039587652802736475
Error 0.0035101225678616744
Error 0.0035101225678616744


In [37]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("error",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    
    l1_error = np.dot(l2_delta,syn1.T)

    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)


error 0.49641003190272537
error 0.008584525653247153
error 0.005789459862507809
error 0.004629176776769983
error 0.005789459862507809
error 0.004629176776769983
error 0.0039587652802736475
error 0.0035101225678616744
error 0.0039587652802736475
error 0.0035101225678616744


In [3]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error",np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)

    l1_error = np.dot(l2_delta,syn1.T)

    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676
Error 0.0039587652802736475
Error 0.003510122567861676


In [6]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error",np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)
    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676
Error 0.0039587652802736475
Error 0.003510122567861676


In [10]:
import numpy as np

def nonlin(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error", np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*(nonlin(l1,True))

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)


Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676
Error 0.0039587652802736475
Error 0.003510122567861676


In [15]:
import numpy as np

def nonlin(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error",+np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676
Error 0.0039587652802736475
Error 0.003510122567861676


In [2]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random ((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range(60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if(i% 10000) == 0:
        print("Error",np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)


Error 0.500877203747751
Error 0.5009165789360368
Error 0.5008926906676552
Error 0.5008408116939934
Error 0.5007828637633553
Error 0.5007275039408033


In [3]:
import numpy as np

def nonlin(x,deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if(i% 10000) == 0:
        print('Error',np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676


In [5]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array ([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error:",np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)
    
    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error: 0.4964100319027255
Error: 0.008584525653247152
Error: 0.0057894598625078085
Error: 0.004629176776769983
Error: 0.0039587652802736475
Error: 0.003510122567861676


In [10]:
import numpy as np

def nonlin(x, deriv = False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1,],
              [1,0,1],
              [1,1,1]])

y = np.array([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range (60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
     print("Error:",np.mean(np.abs(l2_error)))

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)

Error: 0.4964100319027255
Error: 0.008584525653247152
Error: 0.0057894598625078085
Error: 0.004629176776769983
Error: 0.0039587652802736475
Error: 0.003510122567861676


In [15]:
import numpy as np

def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array ([[0,1,1,0]]).T

np.random.seed(1)

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for i in range(60000):
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2

    if (i% 10000) == 0:
        print("Error",np.mean(np.abs(l2_error))) 

    l2_delta = l2_error*nonlin(l2,True)
    l1_error = np.dot(l2_delta,syn1.T)
    l1_delta = l1_error*nonlin(l1,True)

    syn1 += np.dot(l1.T,l2_delta)
    syn0 += np.dot(l0.T,l1_delta)
       


Error 0.4964100319027255
Error 0.008584525653247152
Error 0.0057894598625078085
Error 0.004629176776769983
Error 0.0039587652802736475
Error 0.003510122567861676
